CREATE DATABASE crypto_app;
CREATE ROLE crypto_app_user WITH LOGIN PASSWORD 'STRONG_PASSWD';
\c crypto_app 
GRANT ALL PRIVILEGES ON DATABASE crypto_app TO crypto_app_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO crypto_app_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO crypto_app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO crypto_app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO crypto_app_user;
GRANT ALL ON SCHEMA public TO crypto_app_user;
